<template>
<div>
    <h3>Copywork Day {{day}} of {{ quotes.length }}</h3>
    <h1>{{ quote }}</h1>
    <table class="table">
        <tr v-for="row of rows">
            <td></td>
        </tr>
        
    </table>
</div>

</template>

<script lang="ts" setup>
import { useRoute } from 'vue-router';
const router = useRoute();

const quotes = [
"In the world of blocks, creativity knows no bounds.",
"Mining deep for diamonds isn't just about the reward; it's about the adventure.",
"In Minecraft, your imagination is your only limit.",
"Every block placed is a step towards building your dream.",
"Surviving the night is just the beginning of your story.",
"Redstone: Where logic meets creativity in the land of blocks.",
"From humble dirt huts to grand castles, every build tells a story.",
"The End is just another beginning in the world of Minecraft.",
"Craft your tools, build your dreams, and explore the infinite.",
"In Minecraft, even the simplest block can create the most complex world.",
"In Minecraft, every block you place is a brushstroke on the canvas of your imagination, crafting worlds limited only by your creativity.",
"Survival in Minecraft is not just about gathering resources; it's about the journey you take to build something extraordinary.",
"In the infinite possibilities of Minecraft, even the smallest idea can grow into a monumental creation.",
"The beauty of Minecraft lies in its simplicity—endless opportunities to create, explore, and survive.",
"In a world made of blocks, the only boundaries are those you set for yourself. Break them and build something incredible.",
"Minecraft teaches us that even the most complex mechanisms start with the simplest redstone circuit.",
"From the first punch of a tree to the grandest castle, every Minecraft adventure is uniquely yours to shape.",
"In Minecraft, the tools you craft are not just for survival, but for building the world of your dreams.",
"Minecraft is more than a game; it's a journey where every step forward is a new discovery, and every setback, a chance to rebuild.",
"The night may be full of dangers, but in Minecraft, it's the perfect time to plan, create, and prepare for the dawn.",
"When you stand up for the weak, you’re not just protecting others; you’re standing up for the values that define us all.",
"The legacy of Honduras is one of resilience, where every challenge is met with courage and unwavering spirit.",
"Honduras’ natural beauty, from lush jungles to pristine beaches, reminds us of the importance of preservation.",
"Tennessee’s rich history and vibrant culture remind us of the importance of preserving what we hold dear.",
"Be Courageous: Don’t be afraid to try new things, even if they seem a little scary at first. Courage is about facing your fears head-on.",
"The mountains of Honduras stand as a symbol of the resilience and strength that define the nation's spirit.",
"Be Adventurous: Explore the world around you, whether it’s your neighborhood, a new book, or a different culture. Adventure leads to discovery.",
"Every mistake is a lesson in disguise—embrace it, learn from it, and use it to build your future.",
"Stay Humble: No matter how much you achieve, always stay humble and remember where you started.",
"Jesus Christ’s teachings on forgiveness remind us that mercy and grace are the keys to true peace and reconciliation.",
"Just as in Minecraft, in life, every step forward is a chance to build something better.",
"The spirit of Tennessee is rooted in resilience, where every challenge is met with determination and heart.",
"Jesus Christ's resurrection is the cornerstone of Christian faith, offering the promise of eternal life to all who believe.",
"In Jesus Christ, we find the perfect example of unconditional love, which calls us to love others as He loved us.",
"The compassion of Jesus Christ for the poor, sick, and lost continues to inspire acts of charity and justice today.",
"The strong protect the weak, not because they have to, but because it’s the right thing to do.",
"When we stand up for the weak, we stand up for justice, equality, and the very fabric of society.",
"Jesus Christ showed that true leadership comes from serving others with humility, compassion, and love.",
"Nathan’s love for learning is a beacon of hope, inspiring others to embrace knowledge and never stop growing.",
"Standing up for the weak isn’t just about bravery; it’s about compassion, empathy, and love in action.",
"The miracles of Jesus Christ demonstrated the boundless power of faith and the profound love of God for humanity.",
"In Honduras, every village has a story, every tradition a history, and every person a deep sense of belonging.",
"Embracing challenges is the first step toward unlocking your potential—just like mining for diamonds.",
"The spirit of Honduras lives in its vibrant traditions, colorful festivals, and the pride of its diverse communities.",
"Nathan’s courage is a testament to his belief that every challenge is an opportunity to grow and learn.",
"Jesus Christ's life was a perfect example of selflessness, teaching us to put others' needs above our own.",
"From the Garifuna rhythms to the Mayan ruins, Honduras is a country where history and culture thrive together.",
"Jesus Christ's message of love and redemption has the power to heal hearts, transform lives, and change the world.",
"Nathan’s courage to face new experiences head-on shows that bravery is not the absence of fear, but the triumph over it.",
"Minecraft shows us that creativity flourishes when we embrace both challenges and opportunities in equal measure.",
"Jesus' sacrifice on the cross was the ultimate expression of love, offering redemption and hope to all humanity.",
"Success isn’t about avoiding failure; it's about learning from each attempt and growing stronger every time.",
"To stand up for the weak is to affirm their dignity and worth, a reflection of our shared humanity.",
"Honduras is a land where ancient history and vibrant modern culture come together in harmony and pride.",
"Nathan’s hard work and dedication inspire those around him to strive for excellence in all they do.",
"A growth mindset transforms 'I can’t' into 'I can learn how,' turning obstacles into stepping stones.",
"Nathan’s kindness creates ripples of positivity, proving that even small acts can have a big impact.",
"With his courageous heart, Nathan faces every challenge with a smile, knowing that growth comes from trying.",
"The teachings of Jesus Christ continue to inspire acts of kindness, humility, and unwavering faith across the world.",
"Through His parables, Jesus Christ imparted timeless wisdom, revealing the kingdom of God to all who believe.",
"Kindness is a universal language that everyone understands, and it has the power to bring people together.",
"In Honduras, the warmth of its people is matched only by the beauty of its mountains, beaches, and ancient ruins.",
"With a growth mindset, even the most difficult tasks are seen as opportunities to develop and improve.",
"Each night survived in Minecraft is a testament to the resilience that fuels every great creation.",
"Keep Growing: Never stop improving yourself. There’s always something new to learn and ways to become a better person.",
"With a heart as big as his dreams, Nathan shows us that true strength lies in kindness and hard work.",
"Be Respectful: Treat others the way you want to be treated. Respect builds strong friendships and positive relationships.",
"Nathan’s laughter is contagious, reminding everyone around him that joy is found in the simplest moments.",
"The teachings of Jesus Christ continue to inspire acts of kindness, humility, and unwavering faith across the world.",
"Nathan’s courage knows no bounds, as he fearlessly explores the world with curiosity and kindness.",
"Work Hard: Put effort into everything you do, whether it’s schoolwork, hobbies, or helping around the house. Hard work pays off!",
"The legacy of Jesus Christ is one of eternal love, guiding humanity toward a path of peace, forgiveness, and salvation.",
"Strength is not measured by how much you can lift, but by how many people you can help.",
"In the vast landscape of Minecraft, the journey of building is just as important as the final creation.",
"In the limitless world of Minecraft, every player has the power to create a universe shaped by their imagination.",
"Nathan’s dedication to learning is an inspiration, proving that a curious mind is the key to a bright future.",
"In Jesus Christ, we find the perfect example of unconditional love, which calls us to love others as He loved us.",
"The impact of Jesus Christ on humanity is immeasurable, as His teachings continue to guide and uplift countless souls.",
"Be a Good Listener: Listen to others with your full attention. You can learn a lot from what people have to say.",
"The greatest strength lies in standing up for the weak, for it takes true courage to defend the defenseless.",
"The measure of a society is how it treats its weakest members; stand up for them and you stand for justice.",
"Tennessee is more than a place; it's a feeling of belonging, where everyone is welcomed with open arms.",
"Jesus Christ showed that true leadership comes from serving others with humility, compassion, and love.",
"When we stand up for the weak, we become a beacon of hope in a world that often forgets compassion.",
"True strength is shown in standing up for those who cannot stand for themselves.",
"Nathan’s hard work and determination show that with effort and perseverance, anything is possible.",
"The history of Honduras is a tapestry woven with resilience, strength, and a deep connection to its roots.",
"In Honduras, every sunrise over the Caribbean Sea is a reminder of the country's endless potential and beauty.",
"In the Volunteer State, we learn that helping others is not just a duty but a way of life ingrained in our spirit.",
"Real heroes are those who use their strength to lift others up, especially the weakest among us.",
"The true joy of Minecraft is in the endless exploration, where every block hides a new possibility.",
"Embrace Learning: Look at every day as an opportunity to learn something new. Lifelong learning keeps your mind sharp and your heart open.",
"In Tennessee, we find that the strength of community is the backbone of every great achievement.",
"Honduras’ cultural richness is evident in its music, dance, and art, which reflect a deep connection to history.",
"The impact of Jesus Christ’s ministry is seen in the countless lives transformed by His message of love and redemption.",
"Nathan’s curiosity drives him to ask questions, explore new ideas, and discover the world with wonder.",
"Nathan’s laughter reminds us that life is full of moments worth celebrating, no matter where we are.",
"Jesus Christ's life was a perfect example of selflessness, teaching us to put others' needs above our own.",
"Nathan’s curiosity is a superpower, driving him to explore new ideas and become a lifelong learner.",
"Standing up for the weak is not just a choice; it’s a responsibility we all share.",
"Kindness is like planting seeds—every act grows into something beautiful that nourishes the world.",
"Through His parables, Jesus Christ imparted timeless wisdom, revealing the kingdom of God to all who believe.",
"Honduras is a land of rich cultural heritage and stunning landscapes, where the spirit of its people shines bright.",
"Be Honest: Always tell the truth and be honest with yourself and others. Honesty is the foundation of trust.",
"To stand up for the weak is to stand on the side of justice, where every person’s worth is recognized.",
"From the Great Smoky Mountains to the music of Nashville, Tennessee is a state where dreams come alive.",
"Kindness costs nothing but means everything to those who receive it, creating ripples of positivity everywhere.",
"Be Creative: Use your imagination to come up with new ideas and solutions. Creativity makes life more interesting.",
"Cherish Friendships: Value your friends and be there for them. Good friendships are built on trust, kindness, and understanding.",
"A growth mindset in life, like in Minecraft, turns every obstacle into a building block for future success.",
"Stay Positive: When things get tough, keep a positive attitude. Believe that you can overcome any challenge.",
"Jesus Christ's message of love and redemption has the power to heal hearts, transform lives, and change the world.",
"With kindness in his heart and a twinkle in his eye, Nathan makes every day an opportunity to spread joy.",
"Honduras reminds us that the most valuable treasures are often found in the culture, history, and spirit of a nation.",
"In His teachings, Jesus Christ emphasized the power of faith to move mountains and transform lives.",
"Courage isn’t just facing your own battles, but defending those who are unable to fight.",
"The love of Jesus Christ is the cornerstone of Christian faith, offering hope, healing, and redemption to the world.",
"Acts of kindness, no matter how small, create a ripple effect that touches hearts and changes lives.",
"The miracles of Jesus Christ demonstrated the boundless power of faith and the profound love of God for humanity.",
"Never Give Up: When faced with challenges, keep going. Persistence is key to achieving your goals.",
"The legacy of Jesus Christ is one of eternal love, guiding humanity toward a path of peace, forgiveness, and salvation.",
"Jesus' sacrifice on the cross was the ultimate expression of love, offering redemption and hope to all humanity.",
"Be the strength for those who have none, and in doing so, you strengthen the bond of human kindness.",
"True power is not in dominating others, but in defending those who cannot defend themselves.",
"In the face of failure, a growth mindset reminds us that every setback is a chance to rebuild stronger.",
"In His teachings, Jesus Christ emphasized the power of faith to move mountains and transform lives.",
"The impact of Jesus Christ on humanity is immeasurable, as His teachings continue to guide and uplift countless souls.",
"The strong are called to protect the weak, for in doing so, they protect the very essence of humanity.",
"Minecraft teaches us that from the smallest block, entire worlds can be created through perseverance.",
"Jesus Christ’s teachings on forgiveness remind us that mercy and grace are the keys to true peace and reconciliation.",
"Be Grateful: Appreciate the little things in life and be thankful for what you have. Gratitude leads to happiness.",
"Stay Curious: Always ask questions and seek out new knowledge. The more you learn, the more interesting the world becomes.",
"Jesus Christ's life was a testament to love, sacrifice, and forgiveness, showing humanity the true path to grace.",
"Christ's resurrection symbolizes victory over death and sin, bringing new life and eternal hope to believers.",
"Choosing kindness over anger builds bridges, heals wounds, and makes the world a better place for all.",
"Find Joy in Laughter: Don’t forget to have fun and laugh. A good sense of humor can brighten any situation.",
"The love of Jesus Christ is the cornerstone of Christian faith, offering hope, healing, and redemption to the world.",
"Nathan’s kindness is a beacon of light, touching lives and making the world a better place, one act at a time.",
"In Minecraft, every block laid down is a step closer to turning dreams into reality—one block at a time.",
"Through His ministry, Jesus Christ taught us that love and compassion are the greatest commandments of all.",
"From the ancient ruins of Copán to the vibrant markets of Tegucigalpa, Honduras tells a story of enduring legacy.",
"The smallest act of kindness can have the biggest impact, changing someone's day or even their life.",
"In every adventure, Nathan finds a new lesson, showing that learning is a journey, not a destination.",
"The compassion of Jesus Christ for the poor, sick, and lost continues to inspire acts of charity and justice today.",
"The forests of Honduras are not just a source of natural beauty but a treasure trove of biodiversity to protect.",
"With every block you place, Minecraft proves that creativity and patience are the keys to mastering any challenge.",
"In a world full of challenges, kindness is the strength that lifts us all to greater heights.",
"Nathan’s curiosity leads him down paths of discovery, where every question brings him closer to wisdom.",
"Be Kind: Treat everyone with kindness and respect. Small acts of kindness can make a big difference in someone’s day.",
"Surviving in Minecraft isn’t just about staying alive; it's about building something greater than yourself.",
"In a world where you can be anything, choose to be kind, and watch how it transforms the lives around you.",
"Nathan’s sense of humor brightens the darkest days, reminding us that laughter is the best medicine.",
"The heart of Tennessee beats in the rhythm of its music, the strength of its people, and the beauty of its land.",
"Be Compassionate: Show empathy for others and try to understand how they feel. Compassion brings people closer together.",
"The legacy of Tennessee is one of courage, kindness, and a deep love for the land and its people.",
"Honduras' beauty lies not just in its landscapes but in the hearts of its people, who embody strength and kindness.",
"In both Honduras and Tennessee, Nathan’s spirit shines bright, lighting up every place he calls home.",
"In a world that can be harsh, be the one who stands up for the weak, showing that love and compassion are the greatest strengths.",
"The impact of Jesus Christ’s ministry is seen in the countless lives transformed by His message of love and redemption.",
"The people of Honduras carry a deep respect for their land, understanding that it is both heritage and legacy.",
"Jesus Christ's resurrection is the cornerstone of Christian faith, offering the promise of eternal life to all who believe.",
"Honduras teaches us that true wealth is found not in material things but in the richness of culture and nature.",
"Jesus Christ’s ministry was marked by inclusivity, showing that God's love extends to all, regardless of status or sin.",
"Honduras’ strength lies in its people, who face challenges with determination and a profound sense of community.",
"Believing in your ability to grow makes every challenge an opportunity, not a roadblock.",
"Injustice anywhere is a threat to justice everywhere; stand up for the weak, and you stand for what is right.",
"Like a beacon, kindness shines brightest in the darkest moments, guiding others toward hope and light.",
"Tennessee’s natural beauty inspires us to cherish and protect the land that gives us so much in return.",
"True kindness is in giving without expecting anything in return, knowing that every act matters.",
"Minecraft’s true magic lies in the endless possibilities that come from a single idea turned into action.",
"Be Responsible: Take responsibility for your actions and choices. Being responsible shows that you’re dependable and trustworthy.",
"Help Others: Be willing to lend a hand to those who need it. Helping others not only makes them feel good, but it also makes you feel good too.",
"In Honduras, the past is alive in the traditions that continue to shape the present and inspire the future.",
"A growth mindset allows you to see challenges as the fuel that drives innovation and creativity.",
"Jesus Christ's life was a testament to love, sacrifice, and forgiveness, showing humanity the true path to grace.",
"Christ's resurrection symbolizes victory over death and sin, bringing new life and eternal hope to believers.",
"Through His ministry, Jesus Christ taught us that love and compassion are the greatest commandments of all.",
"In Tennessee, the beauty of the rolling hills is matched only by the warmth and hospitality of its people.",
"Jesus Christ’s ministry was marked by inclusivity, showing that God's love extends to all, regardless of status or sin.",
"In a world that often overlooks the vulnerable, be the voice that stands up for the voiceless.",

];

const day = router.query.day || 1;
const quote = computed(() => quotes[day-1]);
const rows = computed(() => {
    const count = Math.ceil(quote.value.length / 20)
    return Array.from({ length: count }, (_, i) => i);
});

</script>

<style>
.table {
    width: 100%;
    border-collapse: collapse;
}

.table tr td {
    border-bottom: solid 2px #000;
    height: 100px;
}
</style>